version: '3.9'

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222" # Client default
      - "8222:8222" # Management HTTP
      - "6222:6222" # Clustering
      - "9222:9222" 
    command: "-js -m 8222 -c /conf/ws.conf -DV" # Enable JetStream and Monitoring
    volumes:
      - .nats/data:/var/lib/nats-data
      - .nats/config:/conf